---
# tasks file for apache

 - include_vars: "{{ ansible_os_family }}.yml"

 - include: install_apache_centos.yml 
   when: ansible_distribution == 'CentOS'
 
 - include: install_apache_ubuntu.yml
   when: ansible_distribution == 'Ubuntu'

 - include: copy-centos.yml 
   when: ansible_distribution == 'CentOS'

 - include: copy-ubuntu.yml
   when: ansible_distribution == 'Ubuntu'
